CREATE TABLE user (
id BIGINT(20) NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
update_date DATETIME NULL,
PRIMARY KEY(id),
INDEX INDEX_USER_ID (id));